[project]
name = "stellar-plan"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "argparse>=1.4.0",
    "astropy>=5.2.2",
    "pytz>=2025.1",
    "rich>=13.9.4",
]
